spring.application.name=demo

spring.ai.model.chat=google-genai
spring.ai.google.genai.api-key=
spring.ai.google.genai.chat.options.model=gemini-3.6-flash

spring.security.oauth2.client.registration.github.client-id=
spring.security.oauth2.client.registration.github.client-secret=