// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dsa-mentor/DsaMentorWidget.tsx": () => import("../components/mockups/dsa-mentor/DsaMentorWidget.tsx")
};
